---
abstract: 'Reading XML and providing path information based on a pull-parser'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: '0.3'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Reader
provides:
  DebCnt:
    file: lib/XML/Reader/Testcases.pm
  XML::Reader:
    file: lib/XML/Reader.pm
    version: '0.51'
  XML::Reader::Testcases:
    file: lib/XML/Reader/Testcases.pm
    version: '0.51'
  XML::Reader::Token:
    file: lib/XML/Reader.pm
    version: '0.51'
requires:
  Carp: '0'
  Net::HTTP: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.51'
