---
abstract: 'Reading XML and providing path information based on a pull-parser'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Reader
provides:
  DebCnt:
    file: lib/XML/Reader/Testcases.pm
    version: 0
  XML::Reader:
    file: lib/XML/Reader.pm
    version: 0.47
  XML::Reader::Testcases:
    file: lib/XML/Reader/Testcases.pm
    version: 0.47
  XML::Reader::Token:
    file: lib/XML/Reader.pm
    version: 0.47
requires:
  Carp: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.47
