---
name: XML-Reader
version: 0.30
author:
abstract: Reading XML and providing path information based on a pull-parser
license: perl
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  XML::Reader:
    file: lib/XML/Reader.pm
    version: 0.30
  XML::Reader::Token:
    file: lib/XML/Reader.pm
resources:
  license: http://dev.perl.org/licenses/
