--- #YAML:1.0
name:                XML-Reader
version:             0.08
abstract:            Reading XML and providing path information based on a pull-parser.
license:             ~
author:              
    - Klaus Eichner <klaus03@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    XML::TokeParser:               0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
